Repository cafe-24/cafe-24, pull requests merged in 2023-12, with the labels that each got.

#26 로그인 유저정보 저장 및 즐겨찾기 구현
  app/Test/page.tsx
  app/page.tsx
  components/Header.tsx
  components/Map.tsx
  components/StoreDetial.tsx
  components/admin/upload/AdminUploadForm.tsx
  hooks/useGetImages.ts
  store/userInfoStore.ts
  types/firebase.d.ts
  utils/firebase.ts
Labels: enhancement

#30 햄버거, 사이드바 디자인 수정 및 추가
  README.md
  components/HamburgerMenu.tsx
  components/Intro.tsx
  components/Sidebar.tsx
  components/StoreDetial.tsx
  image.png
  public/intro.png
  styles/intro.css
  tailwind.config.ts
Labels: enhancement

#32 admin 사진 업로드 추가
  components/admin/upload/AdminUploadForm.tsx
  utils/firebase.ts
Labels: enhancement

#35 admin dashboard 데이터 추가
  app/admin/page.tsx
  components/admin/dashboard/AdminDashboard.tsx
  package.json
  utils/firebase.ts
  yarn.lock
Labels: enhancement

#36 제보하기 마커에서 위도/경도 추출 및 위도/경도 기반으로 주소 추출 API 구현
  components/Map.tsx
  components/ReportForm.tsx
  components/admin/report/AdminReportForm.tsx
  components/admin/upload/AdminUploadForm.tsx
  store/reportLocationStore.ts
  types/Map.d.ts
  utils/naver.ts
Labels: enhancement

#38 제보하기/제보승인/제보반려 기능 구현 및 404 페이지 제작
  app/admin/[slug]/page.tsx
  app/admin/page.tsx
  app/not-found.tsx
  components/LoginStatus.tsx
  components/Map.tsx
  components/ReportButton.tsx
  components/ReportForm.tsx
  components/Sidebar.tsx
  components/StoreDetial.tsx
  components/admin/report/AdminReportForm.tsx
  components/admin/report/AdminSidebar.tsx
  constants/admin.ts
  store/ReportClickStore.ts
  store/reportStore.ts
  tailwind.config.ts
  types/firebase.d.ts
  utils/admin.ts
  utils/firebase.ts
Labels: enhancement

#39 카페사진 모달 스와이퍼 구현 및 백오피스 디자인 수정
  components/ImageSwiper.tsx
  components/Intro.tsx
  components/LoginStatus.tsx
  components/Map.tsx
  components/StoreDetial.tsx
  components/admin/AdminHeader.tsx
  components/admin/dashboard/AdminDashboard.tsx
  components/admin/report/AdminReportForm.tsx
  components/admin/report/AdminSidebar.tsx
  public/intro.png
  public/intro.webp
  styles/swiper.css
  tailwind.config.ts
Labels: enhancement

#41 헤더 및 사이드바 반응형 구현 및 ios배포 오류 해결
  app/globals.css
  components/HamburgerMenu.tsx
  components/Header.tsx
  components/Intro.tsx
  components/LoginStatus.tsx
  components/Map.tsx
  components/Sidebar.tsx
  components/StoreDetial.tsx
  components/admin/report/AdminSidebar.tsx
  public/intro.png
  tailwind.config.ts
Labels: enhancement

#43 헤더 및 사이드바 반응형 레이아웃 구현
  app/globals.css
  components/Header.tsx
  components/LoginStatus.tsx
  components/Map.tsx
  components/Sidebar.tsx
  components/StoreDetial.tsx
Labels: enhancement

#44 tailwind class 정렬(HeadWind) 및 코드 스타일 간소화
  app/not-found.tsx
  components/HamburgerMenu.tsx
  components/Header.tsx
  components/ImageSwiper.tsx
  components/Intro.tsx
  components/LoginStatus.tsx
  components/Map.tsx
  components/ReportForm.tsx
  components/Sidebar.tsx
  components/StoreDetial.tsx
  components/admin/AdminHeader.tsx
  components/admin/dashboard/AdminDashboard.tsx
  components/admin/report/AdminReportForm.tsx
  components/admin/report/AdminSidebar.tsx
  components/admin/upload/AdminUploadForm.tsx
  components/admin/upload/CheckBox.tsx
  constants/admin.ts
  tailwind.config.ts
  types/Map.d.ts
Labels: enhancement

#45 모바일 테스트 및 모바일 디자인 수정
  app/globals.css
  app/layout.tsx
  components/Header.tsx
  components/Intro.tsx
  components/Map.tsx
  components/ReportButton.tsx
  components/ReportForm.tsx
  components/Sidebar.tsx
  public/googleIcon.ico
  tailwind.config.ts
Labels: enhancement

#46 로그 제거 및 서치콘솔 태그 추가
  app/globals.css
  app/layout.tsx
  components/Map.tsx
  components/admin/dashboard/AdminDashboard.tsx
  tailwind.config.ts
  utils/firebase.ts
Labels: documentation

#47 Metadata 작성 및 SEO 최적화 작업
  app/layout.tsx
  app/page.tsx
  app/robots.ts
  app/sitemap.ts
Labels: enhancement

#48 robots.txt 생성
  app/robots.ts
  app/sitemap.ts
  image.png
  robots.txt
  sitemap.xml
Labels: documentation

#49 업데이트 날짜 불러오기 추가
  components/Intro.tsx
  utils/firebase.ts
Labels: enhancement

#50 README 작성 및 제보하기 오류 수정
  README.md
  components/ReportForm.tsx
Labels: bug, enhancement

#51 admin 정보수정 디자인 추가
  app/admin/[slug]/page.tsx
  app/layout.tsx
  components/ImageSwiper.tsx
  components/ReportForm.tsx
  components/StoreDetial.tsx
  components/admin/modify/AdminModify.tsx
  components/admin/modify/AdminModifyStoreList.tsx
Labels: enhancement

#52 모바일 현위치 추가 및 마커 anchor 설정 등
  README.md
  components/Map.tsx
  styles/marker.css
Labels: enhancement

#53 매장추가 및 제보승인에 업로드 날짜 추가
  store/selectedStore.ts
  types/firebase.d.ts
  utils/firebase.ts
Labels: enhancement

#54 오타 수정
  utils/firebase.ts
Labels: bug

#55 marker design 변경
  styles/marker.css
Labels: enhancement

#56 정보수정 검색 및 리스트 추가
  components/admin/modify/AdminModify.tsx
  components/admin/modify/AdminModifyStoreList.tsx
  components/admin/upload/AdminUploadForm.tsx
Labels: enhancement

#58 어드민 정보수정 이미지 추가 삭제 구현
  components/admin/modify/AdminModify.tsx
  components/admin/modify/AdminModifyStoreList.tsx
  utils/firebase.ts
Labels: enhancement

#59 매장 삭제 전 confirm 추가 및 이미지 저장 시, name 형식 변경
  components/admin/modify/AdminModifyStoreList.tsx
  utils/firebase.ts
Labels: enhancement

#60 대시보드 카페별 색상 추가
  components/admin/dashboard/AdminDashboard.tsx
Labels: enhancement
